// ABOUTME: Go Wish protocol configuration — 36 end-of-life care cards
// ABOUTME: Defines cards, Sanders demographics, and card matching strategy

import { Protocol } from '../domain/protocols/types';

export const GO_WISH_PROTOCOL: Protocol = {
  id: 'go-wish',
  name: 'Go Wish',
  description: 'End-of-life care priorities card sorting activity',
  instruments: [
    {
      id: 'go-wish-cards',
      name: 'Go Wish Cards',
      referenceItems: [
        'To be free from pain',
        'To be at peace with God',
        'To pray',
        'To be mentally aware',
        'Not being a burden to my family',
        'To keep my sense of humor',
        'Not being short of breath',
        'To trust my doctor',
        'To maintain my dignity',
        'To have my family with me',
        'Not being connected to machines',
        'To be treated the way I want',
        'To be kept clean',
        'To be able to help others',
        'To have a nurse I feel comfortable with',
        'To be free from anxiety',
        'To say goodbye to important people in my life',
        'To have a doctor who knows me as a whole person',
        'To have human touch',
        'To prevent arguments by making sure my family knows what I want',
        'To have my funeral arrangements made',
        'Wild Card',
        'To feel that my life is complete',
        'To have an advocate who knows my values and priorities',
        'To know how my body will change',
        'To have someone who will listen to me',
        'To be able to talk about what death means',
        'To have my financial affairs in order',
        'To have my family prepared for my death',
        'To remember personal accomplishments',
        'To meet with clergy or a chaplain',
        'To die at home',
        'Not dying alone',
        'To be able to talk about what scares me',
        'To take care of unfinished business with family and friends',
        'To have close friends near',
      ],
    },
  ],
  participantSchema: [
    { name: 'age', label: 'Age', type: 'number', required: true },
    {
      name: 'race',
      label: 'Race/Ethnicity',
      type: 'select',
      options: ['White', 'Black/African American', 'Hispanic/Latino', 'Asian', 'Native American', 'Pacific Islander', 'Other'],
      required: true,
    },
    {
      name: 'medicalConditions',
      label: 'Medical Conditions',
      type: 'multiselect',
      options: ['Cancer', 'Heart Disease', 'COPD', 'Diabetes', 'Kidney Disease', 'Dementia', 'Stroke', 'Other'],
      required: false,
    },
    {
      name: 'education',
      label: 'Education',
      type: 'select',
      options: ['Less than high school', 'High school/GED', 'Some college', "Bachelor's degree", 'Graduate degree'],
      required: true,
    },
    {
      name: 'householdIncome',
      label: 'Household Income',
      type: 'select',
      options: ['Under $25,000', '$25,000-$49,999', '$50,000-$74,999', '$75,000-$99,999', '$100,000+'],
      required: true,
    },
    {
      name: 'selfAssessedHealth',
      label: 'Self-Assessed Health',
      type: 'select',
      options: ['Excellent', 'Very Good', 'Good', 'Fair', 'Poor'],
      required: true,
    },
  ],
  strategies: [
    {
      id: 'card-matching',
      name: 'Card Matching',
      prompt: 'Extract all Go Wish cards visible in this image. Return JSON with format: {"cards": [{"text": "card text here"}]}. List every card you can read.',
    },
  ],
};
